# Package metadata
name: owl_mediator
description: An implementation of the architectural mediator pattern, with CQRS support.
version: 1.0.1
homepage: https://github.com/owl-shed/dart-mediator
repository: https://github.com/owl-shed/dart-mediator
topics:
  - architecture
  - clean-architecture
  - cross-platform
  - async
  - mediator

# Author info
funding:
  - https://ko-fi.com/nightowl286
  - https://github.com/sponsors/nightowl286

# Package details
environment:
  sdk: ^3.10.8

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
